SCREEN_TITLE = "Flawless"
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 480

HORIZONTAL_VIEWPORT_MARGIN = SCREEN_WIDTH // 2
VERTICAL_VIEWPORT_MARGIN = SCREEN_HEIGHT // 2

TILE_SPRITE_SCALING = 1
PLAYER_SCALING = 1

TILE_SIZE = 32 * TILE_SPRITE_SCALING

INGAME_UI_FONT = "game/assets/fonts/NewTegomin-Regular.ttf"
MENU_FONT = "game/assets/fonts/NewTegomin-Regular.ttf"

CREDITS_FONT = MENU_FONT
WIN_FONT = MENU_FONT
INSTRUCTIONS_FONT = MENU_FONT
SETTINGS_FONT = MENU_FONT
PAUSE_FONT = MENU_FONT
