SCREEN_TITLE = "You better run..."
SCREEN_WIDTH = 960
SCREEN_HEIGHT = 480

HORIZONTAL_VIEWPORT_MARGIN = SCREEN_WIDTH // 2
VERTICAL_VIEWPORT_MARGIN = SCREEN_HEIGHT // 2


TILE_SPRITE_SCALING = 4
PLAYER_SCALING = 1

TILE_SIZE = 8 * TILE_SPRITE_SCALING
